### ISSUE TITLE
How to put directory of shapefiles for use in Geoserver 

### ISSUE THREAD

**Issue by davegis** [meggsimum/geoserver-docker#1]
Hello,

I'm attempting to transfer files using filezilla. Where do I transfer my directory of shapefiles? I'm using Ubuntu 16.04 LTS OS. When I lookup Data Store location it's doesn't look like the same directory tree.

Thanks

**Comment by chrismayer** [comment]
I normally mount the `geoserver_data` folder when starting the container like described [here](https://stackoverflow.com/a/23455537)

e.g.: `docker run -v ./geoserver_mnt/geoserver_data:/opt/geoserver_data/ ...`

Then you can just copy the data into the mounted folder on the host system.

Alternatively you can copy the data into the running container (check [here](https://stackoverflow.com/a/31971697)). But this is not persistent and thus maybe not the preferrable way.

A third way could be using the [GeoServer Importer extension](https://docs.geoserver.org/stable/en/user/extensions/importer/index.html), but I never used it.
