### ISSUE TITLE
Add support for version 2.20.6

### ISSUE THREAD

**Issue by JakobMiksch** [meggsimum/geoserver-docker#22]
https://geoserver.org/announcements/2022/09/15/geoserver-2-20-6-released.html

**Comment by hbruch** [comment]
[Docker hub](https://hub.docker.com/r/meggsimum/geoserver/tags) lists already 2.23.0, so this issue can be closed, no?
Or, since the last publish was 7 months ago, updated to support the [latest 2.24.0 / 2.23.3 versions](https://github.com/geoserver/geoserver/tags)

**Comment by JakobMiksch** [comment]
@hbruch yes, indeed. I am closing
